In [66]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [67]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [68]:
scalar.ndim

0

In [69]:
scalar.item()

7

In [70]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [71]:
vector.ndim

1

In [72]:
vector.shape

torch.Size([2])

In [73]:
#matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])

In [74]:
matrix.ndim

2

In [75]:
matrix.shape

torch.Size([2, 2])

In [76]:
matrix[1]

tensor([ 9, 10])

In [77]:
#tensor
tensor = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [78]:
tensor.ndim

3

In [79]:
tensor.shape

torch.Size([1, 3, 3])

In [80]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
### Random tensors

In [82]:
random_tensor = torch.rand(3, 4)

In [83]:
random_tensor

tensor([[0.4847, 0.1831, 0.2814, 0.4567],
        [0.3370, 0.4368, 0.8412, 0.9846],
        [0.2784, 0.2158, 0.3674, 0.5671]])

In [84]:
random_tensor.ndim

2

In [85]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [86]:
# tensor zeros and ones
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [87]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [88]:
# a range tensors
one_to_ten = torch.arange(start=1, end=1e1+1, step=1)
one_to_ten

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [89]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [91]:
float_32_tensor.dtype

torch.float32

In [92]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [93]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [94]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [95]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

In [96]:
# getting information fom tensors

In [97]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"type: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

tensor([[0.3665, 0.6694, 0.6673, 0.9106],
        [0.9511, 0.4527, 0.3944, 0.8039],
        [0.1975, 0.9797, 0.5796, 0.7461]])
type: torch.float32
shape: torch.Size([3, 4])
device: cpu


In [98]:
# tensor operations

In [99]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [100]:
tensor

tensor([1, 2, 3])

In [101]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [102]:
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [103]:
torch.mul(tensor, 10)

tensor([10., 20., 30.])